### PR TITLE
ci: remove unused workflow file

### PR DESCRIPTION
**Pull request by baiyutang**

### CODE REVIEW

**Comment by lizhemingi** [comment]
I am not quite familiar with CI config, could you please take a look ? @GuangmingLuo

**Comment by GuangmingLuo** [comment]
Why this file is not used? release-check.yml

**Comment by GuangmingLuo** [comment]
The project template is here: https://github.com/cloudwego/.github/tree/main/.github/workflows

**Comment by baiyutang** [comment]
> Why this file is not used? release-check.yml

As @YangruiEmma  explain it:
```
可以去掉，这个是用于确认版本号的;
扩展库也不发版;
也没有版本号文件;
```
I found it always fail, so I check it with her.

**Comment by GuangmingLuo** [comment]
OK，去了也行，也不影响发版

**Review by GuangmingLuo — APPROVED** [review]

**Pull request merged**
