### PR TITLE
fix resolve collision bug when serviceNames have the same prefix

### PR DESCRIPTION
**Pull request by succulentxb**
kitex-contrib/registry-etcd in current version facing at the bug that services will be resolved chaotically when services have names with the same prefix.
For example, 
Service A named "demo-service"
Service B named "demo-service-B"
the resolver will return both Service A and Service B registry info when resolve for "demo-service".

### CODE REVIEW

**Comment by lizhemingi** [comment]
Nice catch. 

But it seems still wrongly for `demo-service` and `demo-service/b`. How about adding a check to ensure character `/` not in service name when register ?

**Comment by GuangmingLuo** [comment]
@succulentxb hi, will you continue on this PR ?

**Comment by succulentxb** [comment]
> @succulentxb hi, will you continue on this PR ?

Sorry for omission, I've push a new commit for checking char '/' in service name.

**Comment by GuangmingLuo** [comment]
@succulentxb please also fix this 
image

**Comment by succulentxb** [comment]
> @succulentxb please also fix this image

done

**Comment by lizhemingi** [comment]
LGTM

**Comment by lizhemingi** [comment]
@succulentxb Could you also help to fix the CI failure?  Just add a check for the return value of `pem.Encode` in `etcd_resolver_test.go`

**Comment by succulentxb** [comment]
@lizhemingi Is it okay that I assign return error to '_' in order to fix ci lint?

**Comment by lizhemingi** [comment]
@succulentxb Thanks.

**Pull request merged**
